### ISSUE TITLE
Not compatible with Terraform v0.12 and the new state pattern

### ISSUE THREAD

**Issue by pitthecat** [adammck/terraform-inventory#113]
Hi there,

the Terraform v0.12 update broke terraform-inventory. It can no longer read or interprete the new state file pattern.

Error Message:
Usage: terraform-inventory [options] path
path: this is either a path to a state file or a folder from which `terraform commands` are valid

With best regards

**Comment by adammck** [comment]
I'm probably not going to get to this any time soon, because I'm busy with other things. Pull requests to fix this would be greatly appreciated. Per [the changelog](https://github.com/hashicorp/terraform/blob/v0.12.0/CHANGELOG.md) it looks like we ought to be running [`terraform show -json`](https://www.terraform.io/docs/commands/show.html#json-output) to fetch the state in JSON format now, rather than reading the file directly.

**Comment by AndiDog** [comment]
I'm currently actively working on this since yesterday afternoon, using @adammck's above suggestion of using `terraform show -json` and trying to stay compatible with both versions (thanks to unit tests 👍).

**Comment by astubbs** [comment]
Fixed in https://github.com/adammck/terraform-inventory/pull/114 - check out that branch and try it - works for me.

**Comment by adammck** [comment]
Fixed by #114.
